--------------------------------------------------------
--  File created - Tuesday-April-05-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_APPLICATION
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_APPLICATION"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 10 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence SEQ_AUTHORITIES
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_AUTHORITIES"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 91 CACHE 10 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence SEQ_EDUCATION
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_EDUCATION"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 10 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence SEQ_EMPLOY
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_EMPLOY"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence SEQ_EMPLOYER
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_EMPLOYER"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 10 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ORGANIZATION
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_ORGANIZATION"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence SEQ_POSITION
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_POSITION"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 31 CACHE 10 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence SEQ_POSITION_GROUP
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_POSITION_GROUP"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence SEQ_STUDENT
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_STUDENT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 10 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence SEQ_USERS
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_USERS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 141 CACHE 10 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence SEQ_WORK
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_WORK"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 111 CACHE 10 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Table APPLICATION
--------------------------------------------------------

  CREATE TABLE "APPLICATION" 
   (	"APPLICATION_ID" NUMBER, 
	"USERNAME" VARCHAR2(20 BYTE), 
	"POSITION_ID" NUMBER, 
	"APPLICATION_STATUS" CHAR(1 BYTE) DEFAULT 0, 
	"CREATE_TIME" DATE, 
	"UPDATE_TIME" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "APPLICATION"."APPLICATION_STATUS" IS '1:request;2:confirm;
3:reject';
--------------------------------------------------------
--  DDL for Table AUTHORITIES
--------------------------------------------------------

  CREATE TABLE "AUTHORITIES" 
   (	"AUTHORITIES_ID" NUMBER, 
	"USERNAME" VARCHAR2(50 BYTE), 
	"AUTHORITY" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EDUCATION
--------------------------------------------------------

  CREATE TABLE "EDUCATION" 
   (	"EDUCATION_ID" NUMBER(*,0), 
	"DEGREE" VARCHAR2(500 BYTE), 
	"MAJOR" VARCHAR2(200 BYTE), 
	"GPA" VARCHAR2(5 BYTE), 
	"INSTITUTION" VARCHAR2(200 BYTE), 
	"COUNTRY" VARCHAR2(100 BYTE), 
	"GRADUATION_DATE" VARCHAR2(5 BYTE), 
	"STUDENT_ID" NUMBER(*,0), 
	"CREATE_TIME" DATE, 
	"UPDATE_TIME" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMPLOYER
--------------------------------------------------------

  CREATE TABLE "EMPLOYER" 
   (	"EMPLOYER_ID" NUMBER(*,0), 
	"EMPLOYER_NAME" VARCHAR2(500 BYTE), 
	"EMPLOYER_ADDRESS" VARCHAR2(1000 BYTE), 
	"EMPLOYER_CITY" VARCHAR2(100 BYTE), 
	"EMPLOYER_POST_CODE" VARCHAR2(10 BYTE), 
	"EMPLOYER_COUNTRY" VARCHAR2(100 BYTE), 
	"CONTACTOR_FIRST_NAME" VARCHAR2(50 BYTE), 
	"CONTACTOR_LAST_NAME" VARCHAR2(50 BYTE), 
	"CONTACTOR_POSITION" VARCHAR2(100 BYTE), 
	"EMPLOYER_TELEPHONE" VARCHAR2(20 BYTE), 
	"EMPLOYER_EMAIL" VARCHAR2(50 BYTE), 
	"EMPLOYER_WEBSITE" VARCHAR2(100 BYTE), 
	"EMPLOYER_NOTES" VARCHAR2(1000 BYTE), 
	"EMPLOYER_GROUP_ID" NUMBER(*,0), 
	"CREATE_TIME" DATE, 
	"UPDATE_TIME" DATE, 
	"USERNAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMPLOYER_GROUP
--------------------------------------------------------

  CREATE TABLE "EMPLOYER_GROUP" 
   (	"EMPLOYER_GROUP_ID" NUMBER(*,0), 
	"EMPLOYER_GROUP_TYPE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PERSISTENT_LOGINS
--------------------------------------------------------

  CREATE TABLE "PERSISTENT_LOGINS" 
   (	"USERNAME" VARCHAR2(64 BYTE), 
	"SERIES" VARCHAR2(64 BYTE), 
	"TOKEN" VARCHAR2(64 BYTE), 
	"LAST_USED" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table POSITION
--------------------------------------------------------

  CREATE TABLE "POSITION" 
   (	"POSITION_ID" NUMBER(*,0), 
	"POSITION_NAME" VARCHAR2(500 BYTE), 
	"POSITION_GROUP_ID" NUMBER, 
	"EMPLOYER_ID" NUMBER, 
	"UPDATE_TIME" DATE, 
	"CREATE_TIME" DATE, 
	"POSITION_DESCRIPTION" VARCHAR2(1000 BYTE), 
	"RESPONSIBILITIES" VARCHAR2(1000 BYTE), 
	"REQUIREMENTS" VARCHAR2(1000 BYTE), 
	"SALARY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table POSITION_GROUP
--------------------------------------------------------

  CREATE TABLE "POSITION_GROUP" 
   (	"POSITION_GROUP_ID" NUMBER, 
	"POSITION_GROUP_NAME" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STUDENT
--------------------------------------------------------

  CREATE TABLE "STUDENT" 
   (	"STUDENT_ID" NUMBER(*,0), 
	"FIRST_NAME" VARCHAR2(50 BYTE), 
	"MIDDLE_NAME" VARCHAR2(50 BYTE), 
	"LAST_NAME" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"TELEPHONE" VARCHAR2(20 BYTE), 
	"STATUS" NUMBER(*,0), 
	"GENDER" VARCHAR2(50 BYTE), 
	"SEMESTER_REGISTERED" VARCHAR2(6 BYTE), 
	"REGISTERED_YEAR" VARCHAR2(4 BYTE), 
	"STUDENT_NO" NUMBER, 
	"CREATE_TIME" DATE, 
	"UPDATE_TIME" DATE, 
	"USERNAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "USERS" 
   (	"USER_ID" NUMBER, 
	"USERNAME" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(100 BYTE), 
	"CREATE_TIME" DATE, 
	"ENABLED" CHAR(1 BYTE) DEFAULT 1, 
	"UPDATE_TIME" DATE, 
	"SALT" VARCHAR2(45 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table WORKS
--------------------------------------------------------

  CREATE TABLE "WORKS" 
   (	"WORK_ID" NUMBER(*,0), 
	"COMPANY" VARCHAR2(500 BYTE), 
	"DATES" VARCHAR2(11 BYTE), 
	"TITLE" VARCHAR2(100 BYTE), 
	"DUTIES" VARCHAR2(500 BYTE), 
	"STUDENT_ID" NUMBER(*,0), 
	"CREATE_TIME" DATE, 
	"UPDATE_TIME" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into APPLICATION
SET DEFINE OFF;
Insert into APPLICATION (APPLICATION_ID,USERNAME,POSITION_ID,APPLICATION_STATUS,CREATE_TIME,UPDATE_TIME) values (51,'william',21,'3',to_date('16-04-04','RR-MM-DD'),to_date('16-04-04','RR-MM-DD'));
Insert into APPLICATION (APPLICATION_ID,USERNAME,POSITION_ID,APPLICATION_STATUS,CREATE_TIME,UPDATE_TIME) values (52,'william',25,'2',to_date('16-04-05','RR-MM-DD'),to_date('16-04-05','RR-MM-DD'));
REM INSERTING into AUTHORITIES
SET DEFINE OFF;
Insert into AUTHORITIES (AUTHORITIES_ID,USERNAME,AUTHORITY) values (53,'admin','ROLE_ADMIN');
Insert into AUTHORITIES (AUTHORITIES_ID,USERNAME,AUTHORITY) values (81,'william','ROLE_STUDENT');
Insert into AUTHORITIES (AUTHORITIES_ID,USERNAME,AUTHORITY) values (82,'ibm','ROLE_ORGANIZATION');
REM INSERTING into EDUCATION
SET DEFINE OFF;
Insert into EDUCATION (EDUCATION_ID,DEGREE,MAJOR,GPA,INSTITUTION,COUNTRY,GRADUATION_DATE,STUDENT_ID,CREATE_TIME,UPDATE_TIME) values (51,'other',null,null,null,null,null,71,to_date('16-04-04','RR-MM-DD'),to_date('16-04-04','RR-MM-DD'));
Insert into EDUCATION (EDUCATION_ID,DEGREE,MAJOR,GPA,INSTITUTION,COUNTRY,GRADUATION_DATE,STUDENT_ID,CREATE_TIME,UPDATE_TIME) values (52,'graduate','software','4.0','University of Windsor','China','09/17',71,to_date('16-04-04','RR-MM-DD'),to_date('16-04-04','RR-MM-DD'));
Insert into EDUCATION (EDUCATION_ID,DEGREE,MAJOR,GPA,INSTITUTION,COUNTRY,GRADUATION_DATE,STUDENT_ID,CREATE_TIME,UPDATE_TIME) values (53,'undergraduate','software','4.0','University of Windsor','China','09/09',71,to_date('16-04-04','RR-MM-DD'),to_date('16-04-04','RR-MM-DD'));
REM INSERTING into EMPLOYER
SET DEFINE OFF;
Insert into EMPLOYER (EMPLOYER_ID,EMPLOYER_NAME,EMPLOYER_ADDRESS,EMPLOYER_CITY,EMPLOYER_POST_CODE,EMPLOYER_COUNTRY,CONTACTOR_FIRST_NAME,CONTACTOR_LAST_NAME,CONTACTOR_POSITION,EMPLOYER_TELEPHONE,EMPLOYER_EMAIL,EMPLOYER_WEBSITE,EMPLOYER_NOTES,EMPLOYER_GROUP_ID,CREATE_TIME,UPDATE_TIME,USERNAME) values (11,'ibm',' 401 Sunset Ave','New York','838jib','USA','Michael','Jorden','HR','8378478378','ibm@imis.com','www.ibm.com',' This is a IT company',1,to_date('16-04-04','RR-MM-DD'),to_date('16-04-04','RR-MM-DD'),'ibm');
REM INSERTING into EMPLOYER_GROUP
SET DEFINE OFF;
Insert into EMPLOYER_GROUP (EMPLOYER_GROUP_ID,EMPLOYER_GROUP_TYPE) values (2,'Startup Company');
Insert into EMPLOYER_GROUP (EMPLOYER_GROUP_ID,EMPLOYER_GROUP_TYPE) values (3,'Research Project');
Insert into EMPLOYER_GROUP (EMPLOYER_GROUP_ID,EMPLOYER_GROUP_TYPE) values (4,'MAC Project ');
Insert into EMPLOYER_GROUP (EMPLOYER_GROUP_ID,EMPLOYER_GROUP_TYPE) values (5,'Other');
Insert into EMPLOYER_GROUP (EMPLOYER_GROUP_ID,EMPLOYER_GROUP_TYPE) values (1,'Company');
REM INSERTING into PERSISTENT_LOGINS
SET DEFINE OFF;
REM INSERTING into POSITION
SET DEFINE OFF;
Insert into POSITION (POSITION_ID,POSITION_NAME,POSITION_GROUP_ID,EMPLOYER_ID,UPDATE_TIME,CREATE_TIME,POSITION_DESCRIPTION,RESPONSIBILITIES,REQUIREMENTS,SALARY) values (21,'Software Engineer',2,11,to_date('16-04-04','RR-MM-DD'),to_date('16-04-04','RR-MM-DD'),'At Adoxio (www.adoxio.com), your unique skills, experience and individuality will be greatly valued. You will contribute to the design and development of high-value, web-enabled, CRM-connected business portals using the latest Microsoft technologies including Azure, and Dynamics CRM. You''ll work directly and collaboratively with technical, management, and client teams to deliver high quality development services and welcome opportunities to research and implement new technologies.','Code, test, debug and document software solutions using appropriate processes, tools, frameworks, libraries, patterns, best practices and standards Working on a wide variety of projects from large-to-small for customers in a variety of industries Diagnose and troubleshoot problems with existing solution and resolve these issues in in a timely and accurate manner Work in a team with other developers and Project Managers to develop the best solutions for internal projects and customers Reviewing your own code for quality and participate in code review sessions Scrum with co-workers on problems and help brainstorm best solutions for business requirements','4+ years of HTML, HTML5, CSS, JavaScript and jQuery 3+ years of ASP.NET and C# development Experience with both ASP.NET Web Forms and MVC Experience with database development and design Experience with web deployments and web server technology (Windows Server, IIS) Experience with source control systems such as TFS and Git Understand cloud technology and know about different cloud platforms like Microsoft Azure',700000);
Insert into POSITION (POSITION_ID,POSITION_NAME,POSITION_GROUP_ID,EMPLOYER_ID,UPDATE_TIME,CREATE_TIME,POSITION_DESCRIPTION,RESPONSIBILITIES,REQUIREMENTS,SALARY) values (25,'Application Developer',1,11,to_date('16-04-04','RR-MM-DD'),to_date('16-04-04','RR-MM-DD'),'At Adoxio (www.adoxio.com), your unique skills, experience and individuality will be greatly valued. You will contribute to the design and development of high-value, web-enabled, CRM-connected business portals using the latest Microsoft technologies including Azure, and Dynamics CRM. You''ll work directly and collaboratively with technical, management, and client teams to deliver high quality development services and welcome opportunities to research and implement new technologies.','Code, test, debug and document software solutions using appropriate processes, tools, frameworks, libraries, patterns, best practices and standards Working on a wide variety of projects from large-to-small for customers in a variety of industries Diagnose and troubleshoot problems with existing solution and resolve these issues in in a timely and accurate manner Work in a team with other developers and Project Managers to develop the best solutions for internal projects and customers Reviewing your own code for quality and participate in code review sessions Scrum with co-workers on problems and help brainstorm best solutions for business requirements','3+ years of HTML, HTML5, CSS, JavaScript and jQuery 3+ years of ASP.NET and C# development Experience with both ASP.NET Web Forms and MVC Experience with database development and design Experience with web deployments and web server technology (Windows Server, IIS) Experience with source control systems such as TFS and Git Understand cloud technology and know about different cloud platforms like Microsoft Azure',500000);
REM INSERTING into POSITION_GROUP
SET DEFINE OFF;
Insert into POSITION_GROUP (POSITION_GROUP_ID,POSITION_GROUP_NAME) values (2,'Mobile Development');
Insert into POSITION_GROUP (POSITION_GROUP_ID,POSITION_GROUP_NAME) values (3,'System Development');
Insert into POSITION_GROUP (POSITION_GROUP_ID,POSITION_GROUP_NAME) values (4,'Technical Support
');
Insert into POSITION_GROUP (POSITION_GROUP_ID,POSITION_GROUP_NAME) values (5,'Networking
');
Insert into POSITION_GROUP (POSITION_GROUP_ID,POSITION_GROUP_NAME) values (6,'Data Analysis
');
Insert into POSITION_GROUP (POSITION_GROUP_ID,POSITION_GROUP_NAME) values (7,'Testing');
Insert into POSITION_GROUP (POSITION_GROUP_ID,POSITION_GROUP_NAME) values (8,'Security
');
Insert into POSITION_GROUP (POSITION_GROUP_ID,POSITION_GROUP_NAME) values (9,'Data Management');
Insert into POSITION_GROUP (POSITION_GROUP_ID,POSITION_GROUP_NAME) values (10,'Other');
Insert into POSITION_GROUP (POSITION_GROUP_ID,POSITION_GROUP_NAME) values (1,'Web Development');
REM INSERTING into STUDENT
SET DEFINE OFF;
Insert into STUDENT (STUDENT_ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,EMAIL,TELEPHONE,STATUS,GENDER,SEMESTER_REGISTERED,REGISTERED_YEAR,STUDENT_NO,CREATE_TIME,UPDATE_TIME,USERNAME) values (71,'william','coper','zhang','william@imis.com','9288938932',0,'Male','winter','2016',100000001,to_date('16-04-04','RR-MM-DD'),to_date('16-04-04','RR-MM-DD'),'william');
REM INSERTING into USERS
SET DEFINE OFF;
Insert into USERS (USER_ID,USERNAME,EMAIL,PASSWORD,CREATE_TIME,ENABLED,UPDATE_TIME,SALT) values (104,'admin','admin@d.com','b594510740d2ac4261c1b2fe87850d08',to_date('16-03-20','RR-MM-DD'),'1',to_date('16-03-20','RR-MM-DD'),null);
Insert into USERS (USER_ID,USERNAME,EMAIL,PASSWORD,CREATE_TIME,ENABLED,UPDATE_TIME,SALT) values (131,'william','william@imis.com','396dce51580be56034d8188078c38c94',to_date('16-04-04','RR-MM-DD'),'1',to_date('16-04-04','RR-MM-DD'),null);
Insert into USERS (USER_ID,USERNAME,EMAIL,PASSWORD,CREATE_TIME,ENABLED,UPDATE_TIME,SALT) values (132,'ibm','ibm@imis.com','41334cff98b42af79d898356ba365b2b',to_date('16-04-04','RR-MM-DD'),'1',to_date('16-04-04','RR-MM-DD'),null);
REM INSERTING into WORKS
SET DEFINE OFF;
Insert into WORKS (WORK_ID,COMPANY,DATES,TITLE,DUTIES,STUDENT_ID,CREATE_TIME,UPDATE_TIME) values (101,'HP','09/09-10/15','Software Engineering','Coding',71,to_date('16-04-04','RR-MM-DD'),to_date('16-04-04','RR-MM-DD'));
Insert into WORKS (WORK_ID,COMPANY,DATES,TITLE,DUTIES,STUDENT_ID,CREATE_TIME,UPDATE_TIME) values (102,null,null,null,null,71,to_date('16-04-04','RR-MM-DD'),to_date('16-04-04','RR-MM-DD'));
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TABLE1_PK" ON "POSITION_GROUP" ("POSITION_GROUP_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_COMPANY
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_COMPANY" ON "EMPLOYER" ("EMPLOYER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_EDUCATION_EDUCATION_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_EDUCATION_EDUCATION_ID" ON "EDUCATION" ("EDUCATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_WORK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_WORK" ON "WORKS" ("WORK_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_USERS
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_USERS" ON "USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index AUTHORITIES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AUTHORITIES_PK" ON "AUTHORITIES" ("AUTHORITIES_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_EMAIL_USERS
--------------------------------------------------------

  CREATE UNIQUE INDEX "UK_EMAIL_USERS" ON "USERS" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_USERNAME_USERS
--------------------------------------------------------

  CREATE UNIQUE INDEX "UK_USERNAME_USERS" ON "USERS" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EMPLOY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EMPLOY_PK" ON "APPLICATION" ("APPLICATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_EMPLOYER
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_EMPLOYER" ON "EMPLOYER_GROUP" ("EMPLOYER_GROUP_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_POSITION
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_POSITION" ON "POSITION" ("POSITION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PERSISTENT_LOGINS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PERSISTENT_LOGINS_PK" ON "PERSISTENT_LOGINS" ("SERIES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_STUDENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_STUDENT" ON "STUDENT" ("STUDENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table AUTHORITIES
--------------------------------------------------------

  ALTER TABLE "AUTHORITIES" MODIFY ("AUTHORITY" NOT NULL ENABLE);
  ALTER TABLE "AUTHORITIES" ADD CONSTRAINT "AUTHORITIES_PK" PRIMARY KEY ("AUTHORITIES_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "AUTHORITIES" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "AUTHORITIES" MODIFY ("AUTHORITIES_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table POSITION
--------------------------------------------------------

  ALTER TABLE "POSITION" MODIFY ("CREATE_TIME" NOT NULL ENABLE);
  ALTER TABLE "POSITION" MODIFY ("UPDATE_TIME" NOT NULL ENABLE);
  ALTER TABLE "POSITION" MODIFY ("EMPLOYER_ID" NOT NULL ENABLE);
  ALTER TABLE "POSITION" MODIFY ("POSITION_GROUP_ID" NOT NULL ENABLE);
  ALTER TABLE "POSITION" MODIFY ("REQUIREMENTS" NOT NULL ENABLE);
  ALTER TABLE "POSITION" MODIFY ("RESPONSIBILITIES" NOT NULL ENABLE);
  ALTER TABLE "POSITION" MODIFY ("POSITION_DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "POSITION" ADD CONSTRAINT "PK_POSITION" PRIMARY KEY ("POSITION_ID")
  USING INDEX (CREATE UNIQUE INDEX "IDX_POSITION" ON "POSITION" ("POSITION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" )  ENABLE;
  ALTER TABLE "POSITION" MODIFY ("POSITION_NAME" NOT NULL ENABLE);
  ALTER TABLE "POSITION" MODIFY ("POSITION_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table APPLICATION
--------------------------------------------------------

  ALTER TABLE "APPLICATION" ADD CONSTRAINT "PK_APPLICATION" PRIMARY KEY ("APPLICATION_ID")
  USING INDEX (CREATE UNIQUE INDEX "EMPLOY_PK" ON "APPLICATION" ("APPLICATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" )  ENABLE;
  ALTER TABLE "APPLICATION" MODIFY ("UPDATE_TIME" NOT NULL ENABLE);
  ALTER TABLE "APPLICATION" MODIFY ("CREATE_TIME" NOT NULL ENABLE);
  ALTER TABLE "APPLICATION" MODIFY ("APPLICATION_STATUS" NOT NULL ENABLE);
  ALTER TABLE "APPLICATION" MODIFY ("POSITION_ID" NOT NULL ENABLE);
  ALTER TABLE "APPLICATION" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "APPLICATION" MODIFY ("APPLICATION_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STUDENT
--------------------------------------------------------

  ALTER TABLE "STUDENT" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "STUDENT" MODIFY ("UPDATE_TIME" NOT NULL ENABLE);
  ALTER TABLE "STUDENT" MODIFY ("CREATE_TIME" NOT NULL ENABLE);
  ALTER TABLE "STUDENT" MODIFY ("STUDENT_NO" NOT NULL ENABLE);
  ALTER TABLE "STUDENT" ADD CONSTRAINT "PK_STUDENT" PRIMARY KEY ("STUDENT_ID")
  USING INDEX (CREATE UNIQUE INDEX "IDX_STUDENT" ON "STUDENT" ("STUDENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" )  ENABLE;
  ALTER TABLE "STUDENT" MODIFY ("REGISTERED_YEAR" NOT NULL ENABLE);
  ALTER TABLE "STUDENT" MODIFY ("SEMESTER_REGISTERED" NOT NULL ENABLE);
  ALTER TABLE "STUDENT" MODIFY ("GENDER" NOT NULL ENABLE);
  ALTER TABLE "STUDENT" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "STUDENT" MODIFY ("TELEPHONE" NOT NULL ENABLE);
  ALTER TABLE "STUDENT" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "STUDENT" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "STUDENT" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "STUDENT" MODIFY ("STUDENT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EDUCATION
--------------------------------------------------------

  ALTER TABLE "EDUCATION" MODIFY ("UPDATE_TIME" NOT NULL ENABLE);
  ALTER TABLE "EDUCATION" MODIFY ("CREATE_TIME" NOT NULL ENABLE);
  ALTER TABLE "EDUCATION" ADD CONSTRAINT "PK_EDUCATION" PRIMARY KEY ("EDUCATION_ID")
  USING INDEX (CREATE UNIQUE INDEX "IDX_EDUCATION_EDUCATION_ID" ON "EDUCATION" ("EDUCATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" )  ENABLE;
  ALTER TABLE "EDUCATION" MODIFY ("STUDENT_ID" NOT NULL ENABLE);
  ALTER TABLE "EDUCATION" MODIFY ("EDUCATION_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYER_GROUP
--------------------------------------------------------

  ALTER TABLE "EMPLOYER_GROUP" ADD CONSTRAINT "PK_EMPLOYER_GROUP" PRIMARY KEY ("EMPLOYER_GROUP_ID")
  USING INDEX (CREATE UNIQUE INDEX "IDX_EMPLOYER" ON "EMPLOYER_GROUP" ("EMPLOYER_GROUP_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" )  ENABLE;
  ALTER TABLE "EMPLOYER_GROUP" MODIFY ("EMPLOYER_GROUP_TYPE" NOT NULL ENABLE);
  ALTER TABLE "EMPLOYER_GROUP" MODIFY ("EMPLOYER_GROUP_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table WORKS
--------------------------------------------------------

  ALTER TABLE "WORKS" MODIFY ("UPDATE_TIME" NOT NULL ENABLE);
  ALTER TABLE "WORKS" MODIFY ("CREATE_TIME" NOT NULL ENABLE);
  ALTER TABLE "WORKS" ADD CONSTRAINT "PK_WORK" PRIMARY KEY ("WORK_ID")
  USING INDEX (CREATE UNIQUE INDEX "IDX_WORK" ON "WORKS" ("WORK_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" )  ENABLE;
  ALTER TABLE "WORKS" MODIFY ("STUDENT_ID" NOT NULL ENABLE);
  ALTER TABLE "WORKS" MODIFY ("WORK_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERSISTENT_LOGINS
--------------------------------------------------------

  ALTER TABLE "PERSISTENT_LOGINS" ADD CONSTRAINT "PERSISTENT_LOGINS_PK" PRIMARY KEY ("SERIES")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PERSISTENT_LOGINS" MODIFY ("LAST_USED" NOT NULL ENABLE);
  ALTER TABLE "PERSISTENT_LOGINS" MODIFY ("TOKEN" NOT NULL ENABLE);
  ALTER TABLE "PERSISTENT_LOGINS" MODIFY ("SERIES" NOT NULL ENABLE);
  ALTER TABLE "PERSISTENT_LOGINS" MODIFY ("USERNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table POSITION_GROUP
--------------------------------------------------------

  ALTER TABLE "POSITION_GROUP" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("POSITION_GROUP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "POSITION_GROUP" MODIFY ("POSITION_GROUP_NAME" NOT NULL ENABLE);
  ALTER TABLE "POSITION_GROUP" MODIFY ("POSITION_GROUP_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYER
--------------------------------------------------------

  ALTER TABLE "EMPLOYER" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "EMPLOYER" MODIFY ("EMPLOYER_NAME" NOT NULL ENABLE);
  ALTER TABLE "EMPLOYER" MODIFY ("UPDATE_TIME" NOT NULL ENABLE);
  ALTER TABLE "EMPLOYER" MODIFY ("CREATE_TIME" NOT NULL ENABLE);
  ALTER TABLE "EMPLOYER" MODIFY ("EMPLOYER_GROUP_ID" NOT NULL ENABLE);
  ALTER TABLE "EMPLOYER" MODIFY ("EMPLOYER_WEBSITE" NOT NULL ENABLE);
  ALTER TABLE "EMPLOYER" ADD CONSTRAINT "PK_EMPLOYER" PRIMARY KEY ("EMPLOYER_ID")
  USING INDEX (CREATE UNIQUE INDEX "IDX_COMPANY" ON "EMPLOYER" ("EMPLOYER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" )  ENABLE;
  ALTER TABLE "EMPLOYER" MODIFY ("EMPLOYER_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "EMPLOYER" MODIFY ("EMPLOYER_TELEPHONE" NOT NULL ENABLE);
  ALTER TABLE "EMPLOYER" MODIFY ("CONTACTOR_POSITION" NOT NULL ENABLE);
  ALTER TABLE "EMPLOYER" MODIFY ("CONTACTOR_LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "EMPLOYER" MODIFY ("CONTACTOR_FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "EMPLOYER" MODIFY ("EMPLOYER_COUNTRY" NOT NULL ENABLE);
  ALTER TABLE "EMPLOYER" MODIFY ("EMPLOYER_POST_CODE" NOT NULL ENABLE);
  ALTER TABLE "EMPLOYER" MODIFY ("EMPLOYER_CITY" NOT NULL ENABLE);
  ALTER TABLE "EMPLOYER" MODIFY ("EMPLOYER_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "EMPLOYER" MODIFY ("EMPLOYER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "USERS" ADD CONSTRAINT "UK_EMAIL_USERS" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "USERS" ADD CONSTRAINT "UK_USERNAME_USERS" UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "USERS" MODIFY ("CREATE_TIME" NOT NULL ENABLE);
  ALTER TABLE "USERS" MODIFY ("UPDATE_TIME" NOT NULL ENABLE);
  ALTER TABLE "USERS" ADD CONSTRAINT "PK_USERS" PRIMARY KEY ("USER_ID")
  USING INDEX (CREATE UNIQUE INDEX "IDX_USERS" ON "USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" )  ENABLE;
  ALTER TABLE "USERS" MODIFY ("ENABLED" NOT NULL ENABLE);
  ALTER TABLE "USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "USERS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "USERS" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "USERS" MODIFY ("USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table APPLICATION
--------------------------------------------------------

  ALTER TABLE "APPLICATION" ADD CONSTRAINT "FK_APPLICATION_POSITION" FOREIGN KEY ("POSITION_ID")
	  REFERENCES "POSITION" ("POSITION_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AUTHORITIES
--------------------------------------------------------

  ALTER TABLE "AUTHORITIES" ADD CONSTRAINT "FK_AUTHORITIES_USERS" FOREIGN KEY ("USERNAME")
	  REFERENCES "USERS" ("USERNAME") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EDUCATION
--------------------------------------------------------

  ALTER TABLE "EDUCATION" ADD CONSTRAINT "FK_EDUCATION_STUDENT" FOREIGN KEY ("STUDENT_ID")
	  REFERENCES "STUDENT" ("STUDENT_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLOYER
--------------------------------------------------------

  ALTER TABLE "EMPLOYER" ADD CONSTRAINT "FK_EMPLOYER_EMPLOYER_GROUP" FOREIGN KEY ("EMPLOYER_GROUP_ID")
	  REFERENCES "EMPLOYER_GROUP" ("EMPLOYER_GROUP_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table POSITION
--------------------------------------------------------

  ALTER TABLE "POSITION" ADD CONSTRAINT "FK_POSITION_EMPLOYER" FOREIGN KEY ("EMPLOYER_ID")
	  REFERENCES "EMPLOYER" ("EMPLOYER_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "POSITION" ADD CONSTRAINT "FK_POSITION_GROUP" FOREIGN KEY ("POSITION_GROUP_ID")
	  REFERENCES "POSITION_GROUP" ("POSITION_GROUP_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STUDENT
--------------------------------------------------------

  ALTER TABLE "STUDENT" ADD CONSTRAINT "FK_STUDENT_USERS" FOREIGN KEY ("USERNAME")
	  REFERENCES "USERS" ("USERNAME") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table WORKS
--------------------------------------------------------

  ALTER TABLE "WORKS" ADD CONSTRAINT "FK_WORK_STUDENT" FOREIGN KEY ("STUDENT_ID")
	  REFERENCES "STUDENT" ("STUDENT_ID") ON DELETE CASCADE ENABLE;
